sync_observation_period.py
No interface or testing structures are implemented, but it has been
successfully tested on a dataset local to the author's computer. Ha!
Fixes #1
=> Add sync obs period function

README.md, pedsnetdcc/site_name_transform.py, pedsnetdcc/tests/site_name_transform_test.py
=> Add site name transform and tests

pedsnetdcc/abstract_transform.py, pedsnetdcc/tests/site_name_transform_test.py
=> Fix vocabulary exclusion in modify_metadata

pedsnetdcc/db.py, pedsnetdcc/utils.py
=> Change logging levels on Statement execution errs

pedsnetdcc/db.py, pedsnetdcc/prepdb.py, pedsnetdcc/tests/db_test.py, pedsnetdcc/tests/prepdb_test.py, pedsnetdcc/utils.py
=> Add prepare_database function in prepdb.py

pedsnetdcc/dict_logging.py
=> QueueHandler Python 2 compatibility

pedsnetdcc/__init__.py, pedsnetdcc/foreign_keys.py, pedsnetdcc/tests/foreign_keys_test.py, pedsnetdcc/utils.py
In addition to Aaron's initial work, I added draft error mode handling and tests.
=> Issue 11 - foreign keys

pedsnetdcc/tests/indexes_test.py, pedsnetdcc/tests/primary_keys_test.py, pedsnetdcc/tests/utils_test.py, pedsnetdcc/utils.py
Fixes #51
Fixes #53
Unfortunately, this code needs more refinement. It should probably not
be in utils and also could use much better error handling. The tests are
extremely simple but they are better than nothing. Useable.
=> Add set_logged and vacuum

pedsnetdcc/__init__.py, pedsnetdcc/cleanup.py, pedsnetdcc/foreign_keys.py, pedsnetdcc/indexes.py, pedsnetdcc/merge_site_data.py, pedsnetdcc/prepdb.py, pedsnetdcc/tests/merge_test.py
The merge function is written to the point of creating the unlogged
merged tables. It still needs to get the code to switch the tables
to logged, create the indexes and constraints, and analyze the tables.
Also, a rollback function should be added. And, tests.
=> Add site data merging function

pedsnetdcc/sync_observation_period.py
=> Add vacuum to sync_obs_period

pedsnetdcc/primary_keys.py, pedsnetdcc/schema.py, pedsnetdcc/site_name_transform.py, pedsnetdcc/tests/db_test.py, pedsnetdcc/tests/schema_test.py, pedsnetdcc/tests/transform_runner_test.py, pedsnetdcc/transform_runner.py, pedsnetdcc/utils.py
This is not ready yet; still WIP.
=> Issue 30 - run transformation

pedsnetdcc/__init__.py, pedsnetdcc/id_mapping_transform.py, pedsnetdcc/main.py, pedsnetdcc/merge_site_data.py, pedsnetdcc/transform_runner.py
=> Add merge and transform cli commands

pedsnetdcc/main.py
=> Fix password prompts

pedsnetdcc/prepdb.py
=> Grant create on db to loading_user

pedsnetdcc/id_mapping_transform.py
=> Fix log echoing

pedsnetdcc/__init__.py
This tells pedsnetdcc to preserver id_mappings from previous data cycle
=> Issue-91 Added provider to CONSISTENT_ID_MAP_TABLES constant

pedsnetdcc/age_transform.py, pedsnetdcc/sync_observation_period.py
Change fields ending in _time to _datetime except for observation_period table
=> Change fields ending in _time to _datetime

pedsnetdcc/age_transform.py
V2.6  time_of_birth remaned to birth_datetime in Person table
=> Change time_of_birth to birth_datetime

pedsnetdcc/sync_observation_period.py
Fixed issue with new syntax in Postgres 10
=> Syntax Updated

pedsnetdcc/__init__.py, pedsnetdcc/permissions.py, pedsnetdcc/prepdb.py, pedsnetdcc/transform_runner.py
Please review and merge then delete this branch.
=> Resolve conflicts branch

pedsnetdcc/transform_runner.py
Index_replacement_tables not needed for sites per Hanieh.
=> PROGPEDS-281 removed replacement tables for transform

pedsnetdcc/main.py, pedsnetdcc/partition_measurement.py, pedsnetdcc/views.py
This pull request fixes issue 128 and fixes issue 129. Please check and merge if okay.
=> Isuue 128 129

pedsnetdcc/check_fact_relationship.py
=> Improve fact relationship check
